# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Matthew Dahl
tagline:          'Ph.D. Student at the University of Notre Dame'
description:      'Ph.D. Student at the University of Notre Dame'
url:              https://mattdahl.github.io/matthewdahl
baseurl:          /

links:
  index:          /
  cv:             /cv/
  research:       /research/
  contact:        /contact/

author:
  name:           'Matthew Dahl'
  url:            https://mattdahl.github.io/matthewdahl

# Gems
plugins:
- jekyll-gist
